apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: momo-store
spec:
  source:
    repoURL: https://gitlab.praktikum-services.ru/momo-store-leonid-petrosian/momo-store-helm-chart.git
    path: ./
    targetRevision: HEAD
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
