apiVersion: v1
kind: Secret
type: Opaque
data:
  project: ZGVmYXVsdA==
  name: bW9tby1zdG9yZS1oZWxtLWNoYXJ0
  url: aHR0cHM6Ly9naXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1L21vbW8tc3RvcmUtbGVvbmlkLXBldHJvc2lhbi9tb21vLXN0b3JlLWhlbG0tY2hhcnQuZ2l0
  type: Z2l0
  username: R2l0T3Bz
  password: bnpmMng3NFdRZUhfOS1UcWhleFI=
metadata:
  name: momo-store-helm-chart-repo
  labels:
    argocd.argoproj.io/secret-type: repository
  
