apiVersion: v1
kind: Secret
type: Opaque
data:
  project: ZGVmYXVsdA==
  name: bW9tby1zdG9yZS1oZWxtLWNoYXJ0
  url: aHR0cHM6Ly9naXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1L2FudG9uLWJvcm9kaW5za2l5L2Jvcm9kaW5za2l5LW1vbW8tc3RvcmUtaGVsbS5naXQ=
  type: Z2l0
  username: R2l0T3Bz
  password: bnpmMng3NFdRZUhfOS1UcWhleFI=
metadata:
  name: momo-store-helm-chart-repo
  labels:
    argocd.argoproj.io/secret-type: repository
  
